apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-clone-controller
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "daemonsets"]
    verbs: ["list", "watch", "update"]
