apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-clone-controller
subjects:
  - kind: ServiceAccount
    name: image-clone-controller
    namespace: image-clone-controller
roleRef:
  kind: ClusterRole
  name: image-clone-controller
  apiGroup: rbac.authorization.k8s.io