apiVersion: v1
kind: Secret
metadata:
  name: backup-registry-credentials
  namespace: image-clone-controller
type: Opaque
stringData:
  REGISTRY_NAME: ""
  REPOSITORY_NAME: ""
  REGISTRY_USERNAME: ""
  REGISTRY_PASSWORD: ""